#!/bin/bash
apt-get update && sudo apt-get upgrade -y && sudo apt-get install lvm2 util-linux -y # update and install app
lsblk # list all block devices
ls /dev/ > /tmp/devlist # Save dev to list

VALUE="/dev/"
SW=swap

echo "Enter the first block device"
read VALUE1
VALUE2=$(cat /tmp/devlist | grep -w $VALUE1)
if [ $VALUE2 = $VALUE1 ]
then
  echo "Enter the second block device"
else
  echo "You did not enter block device"
  exit 0
fi
read VALUE3
VALUE4=$(cat /tmp/f1 | grep -w $VALUE3)
if [ $VALUE3 = $VALUE4 ]
then
  echo "Enter the second block device"
else
  echo "You did not enter block device"
  exit 0
fi

VALUE5="$VALUE$VALUE1"
VALUE6="$VALUE$VALUE3"
pvcreate $VALUE5 $VALUE6 # Creating Physical Volumes

echo "Enter gr. name"
read VALUE7
vgcreate $VALUE7 $VALUE5 $VALUE6 # Creating LVM group

echo "Print name and size be Mb. of file system and SWAP, separate by space"
read VALUE8 VALUE9 VALUE10
echo "The name is $VALUE8, size is $VALUE9 GB, SWAP $VALUE10"
lvcreate -n $VALUE8 -L$VALUE9 $VALUE7 # Creating logical volume
mkfs.ext4 -L $VALUE8 $VALUE$VALUE7/$VALUE8 # Creating file system
lvcreate -n $SW -L$VALUE10 $VALUE7 #Creating SWAP
mkswap -L $SW $VALUE$VALUE7/$SW
swapon $VALUE$VALUE7/$SW

echo "Create folder for mount point for example /mnt/target"
read MNT
mkdir $MNT
echo "Mount $MNT"
mount $VALUE$VALUE7/$VALUE8 $MNT

rm /tmp/devlist # Delite temp file

exit 0
