#!/bin/bash
# install iptables-persistent
apt-get install iptables-persistent -y
# Clear existing rules table:
iptables -F
# Allow incoming SSH interface eth0
iptables -A INPUT -p tcp -i eth0 --dport 22 -j ACCEPT
# Prescribes default policies:
iptables -P INPUT DROP
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
# Making protection against Dos attacks:
iptables -A INPUT -p tcp -m tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s -j ACCEPT
# Allows the packets of the protocols tcp \ udp creating new connections:
iptables -A INPUT -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp -m state --state RELATED,ESTABLISHED -j ACCEPT
# Protects our ssh port of brute force
iptables -A INPUT -p tcp --syn --dport 22 -m recent --name radiator --set
iptables -A INPUT -p tcp --syn --dport 22 -m recent --name radiator --update --seconds 30 --hitcount 3 -j DROP
# "Set up IP FORWARDing and Masquerading..."
iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE
iptables --append FORWARD --in-interface eth1 -j ACCEPT
iptables --append FORWARD --in-interface eth1 -j ACCEPT
# "Enables packet forwarding by kernel..."
sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
# iptables-save
iptables-save > /etc/iptables/rules.v4
iptables -L
